// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/debug/debugger_event_metadata.proto

package debug // import "github.com/netbrain/tf-grpc/go/tensorflow/tensorflow/go/core/debug"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Encapsulates per-event data related to debugging.
type DebuggerEventMetadata struct {
	Device               string   `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	OutputSlot           int32    `protobuf:"varint,2,opt,name=output_slot,json=outputSlot,proto3" json:"output_slot,omitempty"`
	NumChunks            int32    `protobuf:"varint,3,opt,name=num_chunks,json=numChunks,proto3" json:"num_chunks,omitempty"`
	ChunkIndex           int32    `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebuggerEventMetadata) Reset()         { *m = DebuggerEventMetadata{} }
func (m *DebuggerEventMetadata) String() string { return proto.CompactTextString(m) }
func (*DebuggerEventMetadata) ProtoMessage()    {}
func (*DebuggerEventMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_debugger_event_metadata_99b9186b8625cb4b, []int{0}
}
func (m *DebuggerEventMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebuggerEventMetadata.Unmarshal(m, b)
}
func (m *DebuggerEventMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebuggerEventMetadata.Marshal(b, m, deterministic)
}
func (dst *DebuggerEventMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebuggerEventMetadata.Merge(dst, src)
}
func (m *DebuggerEventMetadata) XXX_Size() int {
	return xxx_messageInfo_DebuggerEventMetadata.Size(m)
}
func (m *DebuggerEventMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DebuggerEventMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DebuggerEventMetadata proto.InternalMessageInfo

func (m *DebuggerEventMetadata) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *DebuggerEventMetadata) GetOutputSlot() int32 {
	if m != nil {
		return m.OutputSlot
	}
	return 0
}

func (m *DebuggerEventMetadata) GetNumChunks() int32 {
	if m != nil {
		return m.NumChunks
	}
	return 0
}

func (m *DebuggerEventMetadata) GetChunkIndex() int32 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*DebuggerEventMetadata)(nil), "third_party.tensorflow.core.debug.DebuggerEventMetadata")
}

func init() {
	proto.RegisterFile("tensorflow/core/debug/debugger_event_metadata.proto", fileDescriptor_debugger_event_metadata_99b9186b8625cb4b)
}

var fileDescriptor_debugger_event_metadata_99b9186b8625cb4b = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x15, 0x7e, 0x2a, 0xd5, 0x6c, 0x91, 0x40, 0x59, 0x10, 0x85, 0xa9, 0x0b, 0xf6, 0xd0,
	0x37, 0x28, 0x65, 0x60, 0x60, 0x29, 0x1b, 0x8b, 0xe5, 0xd8, 0xb7, 0x8e, 0x45, 0xe2, 0x1b, 0x39,
	0xd7, 0x01, 0xde, 0x82, 0x47, 0x46, 0x76, 0x22, 0x35, 0x8b, 0xe5, 0xfb, 0x1d, 0x9d, 0x6f, 0x38,
	0x6c, 0x47, 0xe0, 0x07, 0x0c, 0xa7, 0x16, 0xbf, 0x85, 0xc6, 0x00, 0xc2, 0x40, 0x1d, 0xed, 0xf4,
	0x5a, 0x08, 0x12, 0x46, 0xf0, 0x24, 0x3b, 0x20, 0x65, 0x14, 0x29, 0xde, 0x07, 0x24, 0x2c, 0x1f,
	0xa9, 0x71, 0xc1, 0xc8, 0x5e, 0x05, 0xfa, 0xe5, 0x67, 0x01, 0x4f, 0x02, 0x9e, 0xab, 0x4f, 0x7f,
	0x05, 0xbb, 0x3d, 0xcc, 0x92, 0xd7, 0xe4, 0x78, 0x9f, 0x15, 0xe5, 0x1d, 0x5b, 0x19, 0x18, 0x9d,
	0x86, 0xaa, 0xd8, 0x14, 0xdb, 0xf5, 0x71, 0xbe, 0xca, 0x07, 0x76, 0x83, 0x91, 0xfa, 0x48, 0x72,
	0x68, 0x91, 0xaa, 0x8b, 0x4d, 0xb1, 0xbd, 0x3e, 0xb2, 0x09, 0x7d, 0xb4, 0x48, 0xe5, 0x3d, 0x63,
	0x3e, 0x76, 0x52, 0x37, 0xd1, 0x7f, 0x0d, 0xd5, 0x65, 0xce, 0xd7, 0x3e, 0x76, 0x2f, 0x19, 0xa4,
	0x7e, 0x8e, 0xa4, 0xf3, 0x06, 0x7e, 0xaa, 0xab, 0xa9, 0x9f, 0xd1, 0x5b, 0x22, 0xfb, 0xc3, 0xe7,
	0xde, 0x3a, 0x6a, 0x62, 0xcd, 0x35, 0x76, 0xc2, 0x03, 0xd5, 0x41, 0x39, 0x2f, 0xe8, 0xf4, 0x6c,
	0x43, 0xaf, 0x85, 0x45, 0xb1, 0xd8, 0x62, 0xf1, 0xb5, 0xb8, 0x58, 0xa6, 0x5e, 0xe5, 0x09, 0x76,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xa6, 0xd8, 0x66, 0x39, 0x01, 0x00, 0x00,
}
