// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/critical_section.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Protocol buffer representing a CriticalSection.
type CriticalSectionDef struct {
	// Name of the critical section handle.
	CriticalSectionName  string   `protobuf:"bytes,1,opt,name=critical_section_name,json=criticalSectionName,proto3" json:"critical_section_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CriticalSectionDef) Reset()         { *m = CriticalSectionDef{} }
func (m *CriticalSectionDef) String() string { return proto.CompactTextString(m) }
func (*CriticalSectionDef) ProtoMessage()    {}
func (*CriticalSectionDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30d8be90fd098b9, []int{0}
}

func (m *CriticalSectionDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriticalSectionDef.Unmarshal(m, b)
}
func (m *CriticalSectionDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriticalSectionDef.Marshal(b, m, deterministic)
}
func (m *CriticalSectionDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriticalSectionDef.Merge(m, src)
}
func (m *CriticalSectionDef) XXX_Size() int {
	return xxx_messageInfo_CriticalSectionDef.Size(m)
}
func (m *CriticalSectionDef) XXX_DiscardUnknown() {
	xxx_messageInfo_CriticalSectionDef.DiscardUnknown(m)
}

var xxx_messageInfo_CriticalSectionDef proto.InternalMessageInfo

func (m *CriticalSectionDef) GetCriticalSectionName() string {
	if m != nil {
		return m.CriticalSectionName
	}
	return ""
}

// Protocol buffer representing a CriticalSection execution.
type CriticalSectionExecutionDef struct {
	// Name of the critical section handle.
	ExecuteInCriticalSectionName string `protobuf:"bytes,1,opt,name=execute_in_critical_section_name,json=executeInCriticalSectionName,proto3" json:"execute_in_critical_section_name,omitempty"`
	// Whether this operation requires exclusive access to its resources,
	// (i.e., no other CriticalSections may request the same resources).
	ExclusiveResourceAccess bool     `protobuf:"varint,2,opt,name=exclusive_resource_access,json=exclusiveResourceAccess,proto3" json:"exclusive_resource_access,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *CriticalSectionExecutionDef) Reset()         { *m = CriticalSectionExecutionDef{} }
func (m *CriticalSectionExecutionDef) String() string { return proto.CompactTextString(m) }
func (*CriticalSectionExecutionDef) ProtoMessage()    {}
func (*CriticalSectionExecutionDef) Descriptor() ([]byte, []int) {
	return fileDescriptor_d30d8be90fd098b9, []int{1}
}

func (m *CriticalSectionExecutionDef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriticalSectionExecutionDef.Unmarshal(m, b)
}
func (m *CriticalSectionExecutionDef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriticalSectionExecutionDef.Marshal(b, m, deterministic)
}
func (m *CriticalSectionExecutionDef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriticalSectionExecutionDef.Merge(m, src)
}
func (m *CriticalSectionExecutionDef) XXX_Size() int {
	return xxx_messageInfo_CriticalSectionExecutionDef.Size(m)
}
func (m *CriticalSectionExecutionDef) XXX_DiscardUnknown() {
	xxx_messageInfo_CriticalSectionExecutionDef.DiscardUnknown(m)
}

var xxx_messageInfo_CriticalSectionExecutionDef proto.InternalMessageInfo

func (m *CriticalSectionExecutionDef) GetExecuteInCriticalSectionName() string {
	if m != nil {
		return m.ExecuteInCriticalSectionName
	}
	return ""
}

func (m *CriticalSectionExecutionDef) GetExclusiveResourceAccess() bool {
	if m != nil {
		return m.ExclusiveResourceAccess
	}
	return false
}

func init() {
	proto.RegisterType((*CriticalSectionDef)(nil), "tensorflow.CriticalSectionDef")
	proto.RegisterType((*CriticalSectionExecutionDef)(nil), "tensorflow.CriticalSectionExecutionDef")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/critical_section.proto", fileDescriptor_d30d8be90fd098b9)
}

var fileDescriptor_d30d8be90fd098b9 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x65, 0x06, 0x04, 0x1e, 0x83, 0x2a, 0x82, 0x60, 0x88, 0x3a, 0x75, 0x21, 0x96, 0x60,
	0x63, 0xa3, 0xa5, 0x08, 0x16, 0x54, 0x85, 0x8d, 0xc5, 0x72, 0x4e, 0x97, 0x60, 0x91, 0xf8, 0xaa,
	0xb3, 0x4d, 0xbb, 0xf0, 0x63, 0xf8, 0x97, 0x8c, 0x88, 0x10, 0x68, 0x1b, 0x24, 0x36, 0x9f, 0xde,
	0xf7, 0xde, 0xc9, 0xef, 0xa4, 0x0a, 0xe8, 0x3c, 0x71, 0xd5, 0xd0, 0x4a, 0x01, 0x31, 0xaa, 0x25,
	0x53, 0xa0, 0x32, 0x56, 0x0a, 0xd8, 0x06, 0x0b, 0xa6, 0xd1, 0x1e, 0x21, 0x58, 0x72, 0x79, 0xa7,
	0x24, 0x72, 0x63, 0x18, 0xdf, 0xc9, 0x64, 0xd6, 0x53, 0x8f, 0xdf, 0xd0, 0x0d, 0x56, 0xc9, 0x85,
	0x1c, 0x0d, 0xbd, 0xda, 0x99, 0x16, 0x53, 0x91, 0x89, 0xc9, 0x61, 0x71, 0x04, 0xbb, 0x96, 0x07,
	0xd3, 0xe2, 0xf8, 0x5d, 0xc8, 0xd3, 0x41, 0xd4, 0x7c, 0x8d, 0x10, 0x7f, 0x32, 0x6f, 0x65, 0x86,
	0xdd, 0x8c, 0xda, 0x3a, 0xfd, 0x5f, 0xfc, 0x59, 0xcf, 0xdd, 0xbb, 0xd9, 0xdf, 0x3d, 0xc9, 0x95,
	0x3c, 0xc1, 0x35, 0x34, 0xd1, 0xdb, 0x57, 0xd4, 0x8c, 0x9e, 0x22, 0x03, 0x6a, 0x03, 0x80, 0xde,
	0xa7, 0x7b, 0x99, 0x98, 0x1c, 0x14, 0xc7, 0xbf, 0x40, 0xd1, 0xeb, 0xd7, 0x9d, 0x3c, 0x7d, 0x93,
	0x29, 0x71, 0x9d, 0x6f, 0xfe, 0x9f, 0x57, 0x6c, 0x5a, 0x5c, 0x11, 0xbf, 0x4c, 0x47, 0x83, 0x65,
	0x8b, 0xaf, 0xae, 0xfc, 0x42, 0x3c, 0xcd, 0x6b, 0x1b, 0x9e, 0x63, 0x99, 0x03, 0xb5, 0xca, 0x61,
	0x28, 0xd9, 0x58, 0xa7, 0x42, 0x75, 0x5e, 0xf3, 0x12, 0x54, 0x4d, 0xdb, 0xf5, 0x6f, 0x3d, 0x6b,
	0xda, 0x3d, 0xc6, 0x87, 0x10, 0xe5, 0x7e, 0x37, 0x5c, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xab,
	0x88, 0x6c, 0xeb, 0xb2, 0x01, 0x00, 0x00,
}
