// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/device_properties.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceProperties struct {
	// Device type (CPU, GPU, ...)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Vendor (Intel, nvidia, ...)
	Vendor string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	// Model (Haswell, K40, ...)
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Core Frequency in Mhz
	Frequency int64 `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Number of cores
	NumCores int64 `protobuf:"varint,5,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	// Version of the tools and libraries used with this device (e.g. gcc 4.9,
	// cudnn 5.1)
	Environment map[string]string `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Number of registers per core.
	NumRegisters int64 `protobuf:"varint,7,opt,name=num_registers,json=numRegisters,proto3" json:"num_registers,omitempty"`
	// L1 cache size in bytes
	L1CacheSize int64 `protobuf:"varint,8,opt,name=l1_cache_size,json=l1CacheSize,proto3" json:"l1_cache_size,omitempty"`
	// L2 cache size in bytes
	L2CacheSize int64 `protobuf:"varint,9,opt,name=l2_cache_size,json=l2CacheSize,proto3" json:"l2_cache_size,omitempty"`
	// L3 cache size in bytes
	L3CacheSize int64 `protobuf:"varint,10,opt,name=l3_cache_size,json=l3CacheSize,proto3" json:"l3_cache_size,omitempty"`
	// Shared memory size per multiprocessor in bytes. This field is
	// applicable to GPUs only.
	SharedMemorySizePerMultiprocessor int64 `protobuf:"varint,11,opt,name=shared_memory_size_per_multiprocessor,json=sharedMemorySizePerMultiprocessor,proto3" json:"shared_memory_size_per_multiprocessor,omitempty"`
	// Memory size in bytes
	MemorySize int64 `protobuf:"varint,12,opt,name=memory_size,json=memorySize,proto3" json:"memory_size,omitempty"`
	// Memory bandwidth in KB/s
	Bandwidth            int64    `protobuf:"varint,13,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceProperties) Reset()         { *m = DeviceProperties{} }
func (m *DeviceProperties) String() string { return proto.CompactTextString(m) }
func (*DeviceProperties) ProtoMessage()    {}
func (*DeviceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_07c4fdb3c62f9732, []int{0}
}

func (m *DeviceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceProperties.Unmarshal(m, b)
}
func (m *DeviceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceProperties.Marshal(b, m, deterministic)
}
func (m *DeviceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceProperties.Merge(m, src)
}
func (m *DeviceProperties) XXX_Size() int {
	return xxx_messageInfo_DeviceProperties.Size(m)
}
func (m *DeviceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceProperties proto.InternalMessageInfo

func (m *DeviceProperties) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DeviceProperties) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DeviceProperties) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *DeviceProperties) GetFrequency() int64 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *DeviceProperties) GetNumCores() int64 {
	if m != nil {
		return m.NumCores
	}
	return 0
}

func (m *DeviceProperties) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *DeviceProperties) GetNumRegisters() int64 {
	if m != nil {
		return m.NumRegisters
	}
	return 0
}

func (m *DeviceProperties) GetL1CacheSize() int64 {
	if m != nil {
		return m.L1CacheSize
	}
	return 0
}

func (m *DeviceProperties) GetL2CacheSize() int64 {
	if m != nil {
		return m.L2CacheSize
	}
	return 0
}

func (m *DeviceProperties) GetL3CacheSize() int64 {
	if m != nil {
		return m.L3CacheSize
	}
	return 0
}

func (m *DeviceProperties) GetSharedMemorySizePerMultiprocessor() int64 {
	if m != nil {
		return m.SharedMemorySizePerMultiprocessor
	}
	return 0
}

func (m *DeviceProperties) GetMemorySize() int64 {
	if m != nil {
		return m.MemorySize
	}
	return 0
}

func (m *DeviceProperties) GetBandwidth() int64 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

type NamedDevice struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Properties           *DeviceProperties `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NamedDevice) Reset()         { *m = NamedDevice{} }
func (m *NamedDevice) String() string { return proto.CompactTextString(m) }
func (*NamedDevice) ProtoMessage()    {}
func (*NamedDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_07c4fdb3c62f9732, []int{1}
}

func (m *NamedDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedDevice.Unmarshal(m, b)
}
func (m *NamedDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedDevice.Marshal(b, m, deterministic)
}
func (m *NamedDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedDevice.Merge(m, src)
}
func (m *NamedDevice) XXX_Size() int {
	return xxx_messageInfo_NamedDevice.Size(m)
}
func (m *NamedDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedDevice.DiscardUnknown(m)
}

var xxx_messageInfo_NamedDevice proto.InternalMessageInfo

func (m *NamedDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedDevice) GetProperties() *DeviceProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceProperties)(nil), "tensorflow.DeviceProperties")
	proto.RegisterMapType((map[string]string)(nil), "tensorflow.DeviceProperties.EnvironmentEntry")
	proto.RegisterType((*NamedDevice)(nil), "tensorflow.NamedDevice")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/device_properties.proto", fileDescriptor_07c4fdb3c62f9732)
}

var fileDescriptor_07c4fdb3c62f9732 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x26, 0x0d, 0xcd, 0xb8, 0x91, 0xa2, 0x15, 0xaa, 0x56, 0x50, 0x89, 0x10, 0x84,
	0x94, 0x4b, 0x63, 0x9a, 0x5c, 0x10, 0x42, 0x1c, 0x5a, 0x72, 0x2c, 0x44, 0xe1, 0xc6, 0xc5, 0xf2,
	0x9f, 0x89, 0xb3, 0xc2, 0xbb, 0x6b, 0x76, 0xd7, 0xa9, 0xdc, 0xc7, 0xe3, 0xa9, 0x38, 0xa2, 0x5d,
	0x9b, 0xd8, 0xc9, 0xa1, 0xb7, 0x99, 0x6f, 0x7e, 0x33, 0x1e, 0x79, 0xbe, 0x85, 0x0f, 0x06, 0x85,
	0x96, 0x6a, 0x9b, 0xcb, 0xc7, 0x20, 0x91, 0x0a, 0x83, 0x42, 0x49, 0x23, 0xe3, 0x72, 0x1b, 0xa4,
	0xb8, 0x67, 0x09, 0x86, 0x85, 0x92, 0x05, 0x2a, 0xc3, 0x50, 0xcf, 0x5d, 0x89, 0x40, 0xdb, 0x31,
	0xfd, 0xd3, 0x87, 0xf1, 0x57, 0xc7, 0xad, 0x0f, 0x18, 0x21, 0xd0, 0x37, 0x55, 0x81, 0xd4, 0x9b,
	0x78, 0xb3, 0xe1, 0xc6, 0xc5, 0xe4, 0x0a, 0x06, 0x7b, 0x14, 0xa9, 0x54, 0xf4, 0xcc, 0xa9, 0x4d,
	0x46, 0x5e, 0xc2, 0x39, 0x97, 0x29, 0xe6, 0xb4, 0xe7, 0xe4, 0x3a, 0x21, 0xd7, 0x30, 0xdc, 0x2a,
	0xfc, 0x5d, 0xa2, 0x48, 0x2a, 0xda, 0x9f, 0x78, 0xb3, 0xde, 0xa6, 0x15, 0xc8, 0x6b, 0x18, 0x8a,
	0x92, 0x87, 0x76, 0x5b, 0x4d, 0xcf, 0x5d, 0xf5, 0x42, 0x94, 0xfc, 0xde, 0xe6, 0xe4, 0x3b, 0xf8,
	0x28, 0xf6, 0x4c, 0x49, 0xc1, 0x51, 0x18, 0x3a, 0x98, 0xf4, 0x66, 0xfe, 0xe2, 0x66, 0xde, 0xee,
	0x3c, 0x3f, 0xdd, 0x77, 0xbe, 0x6a, 0xf9, 0x95, 0x30, 0xaa, 0xda, 0x74, 0x27, 0x90, 0x77, 0x30,
	0xb2, 0x5f, 0x53, 0x98, 0x31, 0x6d, 0x50, 0x69, 0xfa, 0xc2, 0x7d, 0xf1, 0x52, 0x94, 0x7c, 0xf3,
	0x5f, 0x23, 0x53, 0x18, 0xe5, 0xb7, 0x61, 0x12, 0x25, 0x3b, 0x0c, 0x35, 0x7b, 0x42, 0x7a, 0xe1,
	0x20, 0x3f, 0xbf, 0xbd, 0xb7, 0xda, 0x0f, 0xf6, 0x84, 0x8e, 0x59, 0x74, 0x99, 0x61, 0xc3, 0x2c,
	0x8e, 0x99, 0x65, 0x97, 0x81, 0x86, 0x59, 0xb6, 0xcc, 0x1a, 0xde, 0xeb, 0x5d, 0xa4, 0x30, 0x0d,
	0x39, 0x72, 0xa9, 0x2a, 0x07, 0x86, 0x05, 0xaa, 0x90, 0x97, 0xb9, 0x61, 0x85, 0x92, 0x09, 0x6a,
	0x2d, 0x15, 0xf5, 0x5d, 0xef, 0xdb, 0x1a, 0x7e, 0x70, 0xac, 0x1d, 0xb0, 0x46, 0xf5, 0x70, 0x04,
	0x92, 0x37, 0xe0, 0x77, 0x46, 0xd1, 0x4b, 0xd7, 0x07, 0xfc, 0xd0, 0x61, 0xef, 0x11, 0x47, 0x22,
	0x7d, 0x64, 0xa9, 0xd9, 0xd1, 0x51, 0x7d, 0x8f, 0x83, 0xf0, 0xea, 0x0b, 0x8c, 0x4f, 0x7f, 0x21,
	0x19, 0x43, 0xef, 0x17, 0x56, 0x8d, 0x05, 0x6c, 0x68, 0x2f, 0xbd, 0x8f, 0xf2, 0x12, 0x1b, 0x03,
	0xd4, 0xc9, 0xa7, 0xb3, 0x8f, 0xde, 0x34, 0x04, 0xff, 0x5b, 0xc4, 0x31, 0xad, 0x0f, 0x63, 0xed,
	0x23, 0x22, 0x7e, 0xb0, 0x8f, 0x8d, 0xc9, 0x67, 0x80, 0xd6, 0x87, 0x6e, 0x82, 0xbf, 0xb8, 0x7e,
	0xee, 0xa8, 0x9b, 0x0e, 0x7f, 0x17, 0xdf, 0x5d, 0x9d, 0xd6, 0xd7, 0xd6, 0xca, 0xfa, 0xe7, 0x2a,
	0x63, 0x66, 0x57, 0xc6, 0xf3, 0x44, 0xf2, 0x40, 0xa0, 0x89, 0x55, 0xc4, 0x44, 0x60, 0xb6, 0x37,
	0x99, 0x2a, 0x92, 0x20, 0x93, 0x41, 0xe7, 0x71, 0x74, 0xc2, 0x4c, 0x1e, 0x3f, 0x95, 0xbf, 0x9e,
	0x17, 0x0f, 0x5c, 0xb2, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x67, 0x28, 0x50, 0xf4, 0x50, 0x03,
	0x00, 0x00,
}
