// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_serving/config/model_server_config.proto

package tensorflow_serving

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The type of model.
// TODO(b/31336131): DEPRECATED.
type ModelType int32

const (
	ModelType_MODEL_TYPE_UNSPECIFIED ModelType = 0 // Deprecated: Do not use.
	ModelType_TENSORFLOW             ModelType = 1 // Deprecated: Do not use.
	ModelType_OTHER                  ModelType = 2 // Deprecated: Do not use.
)

var ModelType_name = map[int32]string{
	0: "MODEL_TYPE_UNSPECIFIED",
	1: "TENSORFLOW",
	2: "OTHER",
}

var ModelType_value = map[string]int32{
	"MODEL_TYPE_UNSPECIFIED": 0,
	"TENSORFLOW":             1,
	"OTHER":                  2,
}

func (x ModelType) String() string {
	return proto.EnumName(ModelType_name, int32(x))
}

func (ModelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a1532d213e503811, []int{0}
}

// Common configuration for loading a model being served.
type ModelConfig struct {
	// Name of the model.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Base path to the model, excluding the version directory.
	// E.g> for a model at /foo/bar/my_model/123, where 123 is the version, the
	// base path is /foo/bar/my_model.
	//
	// (This can be changed once a model is in serving, *if* the underlying data
	// remains the same. Otherwise there are no guarantees about whether the old
	// or new data will be used for model versions currently loaded.)
	BasePath string `protobuf:"bytes,2,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	// Type of model.
	// TODO(b/31336131): DEPRECATED. Please use 'model_platform' instead.
	ModelType ModelType `protobuf:"varint,3,opt,name=model_type,json=modelType,proto3,enum=tensorflow.serving.ModelType" json:"model_type,omitempty"` // Deprecated: Do not use.
	// Type of model (e.g. "tensorflow").
	//
	// (This cannot be changed once a model is in serving.)
	ModelPlatform string `protobuf:"bytes,4,opt,name=model_platform,json=modelPlatform,proto3" json:"model_platform,omitempty"`
	// Version policy for the model indicating which version(s) of the model to
	// load and make available for serving simultaneously.
	// The default option is to serve only the latest version of the model.
	//
	// (This can be changed once a model is in serving.)
	ModelVersionPolicy *FileSystemStoragePathSourceConfig_ServableVersionPolicy `protobuf:"bytes,7,opt,name=model_version_policy,json=modelVersionPolicy,proto3" json:"model_version_policy,omitempty"`
	// String labels to associate with versions of the model, allowing inference
	// queries to refer to versions by label instead of number. Multiple labels
	// can map to the same version, but not vice-versa.
	//
	// An envisioned use-case for these labels is canarying tentative versions.
	// For example, one can assign labels "stable" and "canary" to two specific
	// versions. Perhaps initially "stable" is assigned to version 0 and "canary"
	// to version 1. Once version 1 passes canary, one can shift the "stable"
	// label to refer to version 1 (at that point both labels map to the same
	// version -- version 1 -- which is fine). Later once version 2 is ready to
	// canary one can move the "canary" label to version 2. And so on.
	VersionLabels map[string]int64 `protobuf:"bytes,8,rep,name=version_labels,json=versionLabels,proto3" json:"version_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// Configures logging requests and responses, to the model.
	//
	// (This can be changed once a model is in serving.)
	LoggingConfig        *LoggingConfig `protobuf:"bytes,6,opt,name=logging_config,json=loggingConfig,proto3" json:"logging_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ModelConfig) Reset()         { *m = ModelConfig{} }
func (m *ModelConfig) String() string { return proto.CompactTextString(m) }
func (*ModelConfig) ProtoMessage()    {}
func (*ModelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1532d213e503811, []int{0}
}

func (m *ModelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelConfig.Unmarshal(m, b)
}
func (m *ModelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelConfig.Marshal(b, m, deterministic)
}
func (m *ModelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelConfig.Merge(m, src)
}
func (m *ModelConfig) XXX_Size() int {
	return xxx_messageInfo_ModelConfig.Size(m)
}
func (m *ModelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ModelConfig proto.InternalMessageInfo

func (m *ModelConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelConfig) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

// Deprecated: Do not use.
func (m *ModelConfig) GetModelType() ModelType {
	if m != nil {
		return m.ModelType
	}
	return ModelType_MODEL_TYPE_UNSPECIFIED
}

func (m *ModelConfig) GetModelPlatform() string {
	if m != nil {
		return m.ModelPlatform
	}
	return ""
}

func (m *ModelConfig) GetModelVersionPolicy() *FileSystemStoragePathSourceConfig_ServableVersionPolicy {
	if m != nil {
		return m.ModelVersionPolicy
	}
	return nil
}

func (m *ModelConfig) GetVersionLabels() map[string]int64 {
	if m != nil {
		return m.VersionLabels
	}
	return nil
}

func (m *ModelConfig) GetLoggingConfig() *LoggingConfig {
	if m != nil {
		return m.LoggingConfig
	}
	return nil
}

// Static list of models to be loaded for serving.
type ModelConfigList struct {
	Config               []*ModelConfig `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ModelConfigList) Reset()         { *m = ModelConfigList{} }
func (m *ModelConfigList) String() string { return proto.CompactTextString(m) }
func (*ModelConfigList) ProtoMessage()    {}
func (*ModelConfigList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1532d213e503811, []int{1}
}

func (m *ModelConfigList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelConfigList.Unmarshal(m, b)
}
func (m *ModelConfigList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelConfigList.Marshal(b, m, deterministic)
}
func (m *ModelConfigList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelConfigList.Merge(m, src)
}
func (m *ModelConfigList) XXX_Size() int {
	return xxx_messageInfo_ModelConfigList.Size(m)
}
func (m *ModelConfigList) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelConfigList.DiscardUnknown(m)
}

var xxx_messageInfo_ModelConfigList proto.InternalMessageInfo

func (m *ModelConfigList) GetConfig() []*ModelConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// ModelServer config.
type ModelServerConfig struct {
	// ModelServer takes either a static file-based model config list or an Any
	// proto representing custom model config that is fetched dynamically at
	// runtime (through network RPC, custom service, etc.).
	//
	// Types that are valid to be assigned to Config:
	//	*ModelServerConfig_ModelConfigList
	//	*ModelServerConfig_CustomModelConfig
	Config               isModelServerConfig_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ModelServerConfig) Reset()         { *m = ModelServerConfig{} }
func (m *ModelServerConfig) String() string { return proto.CompactTextString(m) }
func (*ModelServerConfig) ProtoMessage()    {}
func (*ModelServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1532d213e503811, []int{2}
}

func (m *ModelServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelServerConfig.Unmarshal(m, b)
}
func (m *ModelServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelServerConfig.Marshal(b, m, deterministic)
}
func (m *ModelServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelServerConfig.Merge(m, src)
}
func (m *ModelServerConfig) XXX_Size() int {
	return xxx_messageInfo_ModelServerConfig.Size(m)
}
func (m *ModelServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ModelServerConfig proto.InternalMessageInfo

type isModelServerConfig_Config interface {
	isModelServerConfig_Config()
}

type ModelServerConfig_ModelConfigList struct {
	ModelConfigList *ModelConfigList `protobuf:"bytes,1,opt,name=model_config_list,json=modelConfigList,proto3,oneof"`
}

type ModelServerConfig_CustomModelConfig struct {
	CustomModelConfig *any.Any `protobuf:"bytes,2,opt,name=custom_model_config,json=customModelConfig,proto3,oneof"`
}

func (*ModelServerConfig_ModelConfigList) isModelServerConfig_Config() {}

func (*ModelServerConfig_CustomModelConfig) isModelServerConfig_Config() {}

func (m *ModelServerConfig) GetConfig() isModelServerConfig_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ModelServerConfig) GetModelConfigList() *ModelConfigList {
	if x, ok := m.GetConfig().(*ModelServerConfig_ModelConfigList); ok {
		return x.ModelConfigList
	}
	return nil
}

func (m *ModelServerConfig) GetCustomModelConfig() *any.Any {
	if x, ok := m.GetConfig().(*ModelServerConfig_CustomModelConfig); ok {
		return x.CustomModelConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ModelServerConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ModelServerConfig_ModelConfigList)(nil),
		(*ModelServerConfig_CustomModelConfig)(nil),
	}
}

func init() {
	proto.RegisterEnum("tensorflow.serving.ModelType", ModelType_name, ModelType_value)
	proto.RegisterType((*ModelConfig)(nil), "tensorflow.serving.ModelConfig")
	proto.RegisterMapType((map[string]int64)(nil), "tensorflow.serving.ModelConfig.VersionLabelsEntry")
	proto.RegisterType((*ModelConfigList)(nil), "tensorflow.serving.ModelConfigList")
	proto.RegisterType((*ModelServerConfig)(nil), "tensorflow.serving.ModelServerConfig")
}

func init() {
	proto.RegisterFile("tensorflow_serving/config/model_server_config.proto", fileDescriptor_a1532d213e503811)
}

var fileDescriptor_a1532d213e503811 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x9d, 0xdb, 0xae, 0xb4, 0xae, 0xda, 0x75, 0x66, 0x42, 0xa1, 0x08, 0x28, 0x43, 0x48, 0x15,
	0x12, 0x89, 0x94, 0x3d, 0xf0, 0xf1, 0x80, 0xc6, 0xb6, 0x54, 0xdd, 0xe8, 0xd6, 0x92, 0x14, 0xd0,
	0x78, 0x89, 0x92, 0xe0, 0x64, 0x11, 0x4e, 0x1c, 0xd9, 0x6e, 0x51, 0x1e, 0xf8, 0x15, 0xfc, 0x19,
	0x7e, 0x1a, 0x8f, 0x28, 0x76, 0x0a, 0x19, 0xdb, 0xb4, 0xb7, 0xf8, 0xe4, 0xdc, 0x73, 0xee, 0xf1,
	0xf5, 0x85, 0x7b, 0x02, 0xa7, 0x9c, 0xb2, 0x90, 0xd0, 0xef, 0x2e, 0xc7, 0x6c, 0x15, 0xa7, 0x91,
	0x11, 0xd0, 0x34, 0x8c, 0x23, 0x23, 0xa1, 0x5f, 0x31, 0x91, 0x20, 0x66, 0xae, 0xc2, 0xf4, 0x8c,
	0x51, 0x41, 0x11, 0xfa, 0x57, 0xa4, 0x97, 0x45, 0x83, 0xfb, 0x11, 0xa5, 0x11, 0xc1, 0x86, 0x64,
	0xf8, 0xcb, 0xd0, 0xf0, 0xd2, 0x5c, 0xd1, 0x07, 0xfa, 0xcd, 0x1e, 0x84, 0x46, 0x51, 0x9c, 0x46,
	0x97, 0xe4, 0x07, 0xa7, 0xd7, 0xf0, 0x39, 0x5d, 0xb2, 0x00, 0x73, 0x83, 0x0b, 0xca, 0xbc, 0x08,
	0xbb, 0x99, 0x27, 0x2e, 0x8c, 0x30, 0x26, 0xd8, 0xe5, 0x39, 0x17, 0x38, 0x71, 0xab, 0x3f, 0x5c,
	0xc5, 0x56, 0x72, 0xbb, 0x3f, 0x1b, 0xb0, 0x73, 0x5a, 0x64, 0x39, 0x94, 0x26, 0x08, 0xc1, 0x46,
	0xea, 0x25, 0x58, 0x03, 0x43, 0x30, 0x6a, 0xdb, 0xf2, 0x1b, 0x3d, 0x80, 0x6d, 0xdf, 0xe3, 0xaa,
	0x5a, 0xab, 0xc9, 0x1f, 0xad, 0x02, 0x98, 0x7b, 0xe2, 0x02, 0xed, 0x43, 0xa8, 0xee, 0x42, 0xe4,
	0x19, 0xd6, 0xea, 0x43, 0x30, 0xea, 0x99, 0x0f, 0xf5, 0xab, 0x77, 0xa0, 0x4b, 0x97, 0x45, 0x9e,
	0xe1, 0x83, 0x9a, 0x06, 0xec, 0x76, 0xb2, 0x3e, 0xa2, 0x67, 0xb0, 0xa7, 0x14, 0x32, 0xe2, 0x89,
	0x90, 0xb2, 0x44, 0x6b, 0x48, 0x8f, 0xae, 0x44, 0xe7, 0x25, 0x88, 0x7e, 0xc0, 0x1d, 0x45, 0x5b,
	0x61, 0xc6, 0x63, 0x9a, 0xba, 0x19, 0x25, 0x71, 0x90, 0x6b, 0x77, 0x86, 0x60, 0xd4, 0x31, 0xdf,
	0x5f, 0x67, 0x39, 0x8e, 0x09, 0x76, 0xe4, 0x0d, 0x38, 0xea, 0x02, 0x8a, 0x8e, 0x1d, 0x19, 0x5f,
	0xc5, 0xd5, 0x1d, 0xcc, 0x56, 0x9e, 0x4f, 0xf0, 0x27, 0xa5, 0x39, 0x97, 0x92, 0x36, 0x92, 0x46,
	0x97, 0x30, 0x74, 0x0e, 0x7b, 0x6b, 0x63, 0xe2, 0xf9, 0x98, 0x70, 0xad, 0x35, 0xac, 0x8f, 0x3a,
	0xa6, 0x79, 0x63, 0xd6, 0xd2, 0xa2, 0x94, 0x99, 0xca, 0x22, 0x2b, 0x15, 0x2c, 0xb7, 0xbb, 0xab,
	0x2a, 0x86, 0x26, 0xb0, 0x77, 0x79, 0xd4, 0x5a, 0x53, 0x66, 0x7a, 0x72, 0x9d, 0xf4, 0x54, 0x31,
	0x95, 0xb8, 0xdd, 0x25, 0xd5, 0xe3, 0x60, 0x1f, 0xa2, 0xab, 0x76, 0xa8, 0x0f, 0xeb, 0xdf, 0x70,
	0x5e, 0x8e, 0xb4, 0xf8, 0x44, 0x3b, 0x70, 0x73, 0xe5, 0x91, 0x25, 0x96, 0xd3, 0xac, 0xdb, 0xea,
	0xf0, 0xa6, 0xf6, 0x0a, 0x9c, 0x34, 0x5a, 0x9b, 0xfd, 0xe6, 0xee, 0x09, 0xdc, 0xaa, 0x44, 0x98,
	0xc6, 0x5c, 0xa0, 0x97, 0xb0, 0x59, 0x36, 0x07, 0x64, 0xee, 0xc7, 0xb7, 0xe4, 0xb6, 0x4b, 0xfa,
	0xee, 0x2f, 0x00, 0xb7, 0x25, 0xee, 0xc8, 0x65, 0x29, 0xdf, 0xd9, 0x07, 0xb8, 0xad, 0xa6, 0xa9,
	0x58, 0x2e, 0x89, 0xb9, 0x90, 0x1d, 0x76, 0xcc, 0xa7, 0xb7, 0x28, 0x17, 0xed, 0x4c, 0x36, 0xec,
	0xad, 0xe4, 0xbf, 0x0e, 0xc7, 0xf0, 0x6e, 0xb0, 0xe4, 0x82, 0x26, 0x6e, 0x55, 0x59, 0x46, 0xec,
	0x98, 0x3b, 0xba, 0x5a, 0x41, 0x7d, 0xbd, 0x82, 0xfa, 0xbb, 0x34, 0x9f, 0x6c, 0xd8, 0xdb, 0xaa,
	0xa4, 0x22, 0x7f, 0xd0, 0x5a, 0x27, 0x7d, 0x7e, 0x06, 0xdb, 0x7f, 0x5f, 0x2d, 0x7a, 0x04, 0xef,
	0x9d, 0xce, 0x8e, 0xac, 0xa9, 0xbb, 0x38, 0x9f, 0x5b, 0xee, 0xc7, 0x33, 0x67, 0x6e, 0x1d, 0x1e,
	0x8f, 0x8f, 0xad, 0xa3, 0xfe, 0xc6, 0xa0, 0xd6, 0x02, 0x08, 0x41, 0xb8, 0xb0, 0xce, 0x9c, 0x99,
	0x3d, 0x9e, 0xce, 0x3e, 0xf7, 0x81, 0xc4, 0xba, 0x70, 0x73, 0xb6, 0x98, 0x58, 0x76, 0xbf, 0x56,
	0x1c, 0x0f, 0xde, 0x7e, 0x79, 0x1d, 0xc5, 0xe2, 0x62, 0xe9, 0xeb, 0x01, 0x4d, 0x8c, 0x14, 0x0b,
	0x9f, 0x79, 0x71, 0x6a, 0x88, 0xf0, 0x45, 0xc4, 0xb2, 0xc0, 0x88, 0xa8, 0xb1, 0xde, 0xe8, 0xab,
	0x4b, 0xfe, 0x1b, 0x00, 0xbf, 0x29, 0x9b, 0xdf, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x68,
	0xef, 0xa7, 0x98, 0x04, 0x00, 0x00,
}
