// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_serving/apis/predict.proto

package tensorflow_serving

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	framework "github.com/netbrain/tf-grpc/go/tensorflow/tensorflow/go/core/framework"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PredictRequest specifies which TensorFlow model to run, as well as
// how inputs are mapped to tensors and how outputs are filtered before
// returning to user.
type PredictRequest struct {
	// Model Specification. If version is not specified, will use the latest
	// (numerical) version.
	ModelSpec *ModelSpec `protobuf:"bytes,1,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Input tensors.
	// Names of input tensor are alias names. The mapping from aliases to real
	// input tensor names is stored in the SavedModel export as a prediction
	// SignatureDef under the 'inputs' field.
	Inputs map[string]*framework.TensorProto `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Output filter.
	// Names specified are alias names. The mapping from aliases to real output
	// tensor names is stored in the SavedModel export as a prediction
	// SignatureDef under the 'outputs' field.
	// Only tensors specified here will be run/fetched and returned, with the
	// exception that when none is specified, all tensors specified in the
	// named signature will be run/fetched and returned.
	OutputFilter         []string `protobuf:"bytes,3,rep,name=output_filter,json=outputFilter,proto3" json:"output_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PredictRequest) Reset()         { *m = PredictRequest{} }
func (m *PredictRequest) String() string { return proto.CompactTextString(m) }
func (*PredictRequest) ProtoMessage()    {}
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0799bd5d5992a93, []int{0}
}

func (m *PredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictRequest.Unmarshal(m, b)
}
func (m *PredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictRequest.Marshal(b, m, deterministic)
}
func (m *PredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictRequest.Merge(m, src)
}
func (m *PredictRequest) XXX_Size() int {
	return xxx_messageInfo_PredictRequest.Size(m)
}
func (m *PredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PredictRequest proto.InternalMessageInfo

func (m *PredictRequest) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *PredictRequest) GetInputs() map[string]*framework.TensorProto {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *PredictRequest) GetOutputFilter() []string {
	if m != nil {
		return m.OutputFilter
	}
	return nil
}

// Response for PredictRequest on successful run.
type PredictResponse struct {
	// Effective Model Specification used to process PredictRequest.
	ModelSpec *ModelSpec `protobuf:"bytes,2,opt,name=model_spec,json=modelSpec,proto3" json:"model_spec,omitempty"`
	// Output tensors.
	Outputs              map[string]*framework.TensorProto `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PredictResponse) Reset()         { *m = PredictResponse{} }
func (m *PredictResponse) String() string { return proto.CompactTextString(m) }
func (*PredictResponse) ProtoMessage()    {}
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0799bd5d5992a93, []int{1}
}

func (m *PredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PredictResponse.Unmarshal(m, b)
}
func (m *PredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PredictResponse.Marshal(b, m, deterministic)
}
func (m *PredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PredictResponse.Merge(m, src)
}
func (m *PredictResponse) XXX_Size() int {
	return xxx_messageInfo_PredictResponse.Size(m)
}
func (m *PredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PredictResponse proto.InternalMessageInfo

func (m *PredictResponse) GetModelSpec() *ModelSpec {
	if m != nil {
		return m.ModelSpec
	}
	return nil
}

func (m *PredictResponse) GetOutputs() map[string]*framework.TensorProto {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*PredictRequest)(nil), "tensorflow.serving.PredictRequest")
	proto.RegisterMapType((map[string]*framework.TensorProto)(nil), "tensorflow.serving.PredictRequest.InputsEntry")
	proto.RegisterType((*PredictResponse)(nil), "tensorflow.serving.PredictResponse")
	proto.RegisterMapType((map[string]*framework.TensorProto)(nil), "tensorflow.serving.PredictResponse.OutputsEntry")
}

func init() {
	proto.RegisterFile("tensorflow_serving/apis/predict.proto", fileDescriptor_d0799bd5d5992a93)
}

var fileDescriptor_d0799bd5d5992a93 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xcf, 0x4b, 0xf3, 0x40,
	0x14, 0x24, 0x09, 0x5f, 0x3f, 0xba, 0xed, 0xf7, 0x83, 0x5c, 0x0c, 0x01, 0xa1, 0xb4, 0x28, 0xbd,
	0x74, 0x57, 0xea, 0x45, 0x45, 0x3c, 0x08, 0x16, 0x14, 0xc4, 0x92, 0x7a, 0xf2, 0x52, 0xd2, 0xf4,
	0x25, 0x2e, 0x4d, 0x76, 0xd7, 0xdd, 0x4d, 0x4b, 0xff, 0x0a, 0xff, 0x55, 0x8f, 0x1e, 0xa5, 0xbb,
	0xad, 0xad, 0x56, 0x05, 0xc1, 0xdb, 0xe3, 0xed, 0xcc, 0xce, 0xbc, 0x61, 0xd0, 0x9e, 0x06, 0xa6,
	0xb8, 0x4c, 0x73, 0x3e, 0x1b, 0x2a, 0x90, 0x53, 0xca, 0x32, 0x12, 0x0b, 0xaa, 0x88, 0x90, 0x30,
	0xa6, 0x89, 0xc6, 0x42, 0x72, 0xcd, 0x7d, 0x7f, 0x0d, 0xc3, 0x4b, 0x58, 0xb8, 0xbf, 0xde, 0x91,
	0x84, 0x4b, 0x20, 0xa9, 0x8c, 0x0b, 0x98, 0x71, 0x39, 0x21, 0xf6, 0xc5, 0x72, 0xc3, 0xd6, 0x67,
	0x12, 0x05, 0x1f, 0x43, 0x6e, 0x41, 0xcd, 0x47, 0x17, 0xfd, 0xed, 0x5b, 0xc9, 0x08, 0x1e, 0x4a,
	0x50, 0xda, 0x3f, 0x45, 0xc8, 0x20, 0x86, 0x4a, 0x40, 0x12, 0x38, 0x0d, 0xa7, 0x5d, 0xeb, 0xee,
	0xe2, 0x6d, 0x23, 0xf8, 0x7a, 0x81, 0x1a, 0x08, 0x48, 0xa2, 0x6a, 0xb1, 0x1a, 0xfd, 0x1e, 0xaa,
	0x50, 0x26, 0x4a, 0xad, 0x02, 0xb7, 0xe1, 0xb5, 0x6b, 0x5d, 0xfc, 0x11, 0xf3, 0xad, 0x22, 0xbe,
	0x34, 0x84, 0x0b, 0xa6, 0xe5, 0x3c, 0x5a, 0xb2, 0xfd, 0x16, 0xfa, 0xc3, 0x4b, 0x2d, 0x4a, 0x3d,
	0x4c, 0x69, 0xae, 0x41, 0x06, 0x5e, 0xc3, 0x6b, 0x57, 0xa3, 0xba, 0x5d, 0xf6, 0xcc, 0x2e, 0x8c,
	0x50, 0x6d, 0x83, 0xeb, 0xff, 0x47, 0xde, 0x04, 0xe6, 0xc6, 0x72, 0x35, 0x5a, 0x8c, 0x7e, 0x07,
	0xfd, 0x9a, 0xc6, 0x79, 0x09, 0x81, 0x6b, 0xce, 0xd8, 0xd9, 0x34, 0x73, 0x6b, 0xc6, 0xfe, 0x22,
	0x86, 0xc8, 0xa2, 0x4e, 0xdc, 0x23, 0xa7, 0xf9, 0xe4, 0xa0, 0x7f, 0xaf, 0xfe, 0x94, 0xe0, 0x4c,
	0xc1, 0xbb, 0x48, 0xdc, 0x6f, 0x46, 0x72, 0x85, 0x7e, 0x5b, 0xd7, 0x2a, 0x70, 0x4c, 0x26, 0x07,
	0x5f, 0x66, 0x62, 0x35, 0xf1, 0x8d, 0xa5, 0xd8, 0x54, 0x56, 0x1f, 0x84, 0x03, 0x54, 0xdf, 0x7c,
	0xf8, 0x91, 0x93, 0xcf, 0xcf, 0xee, 0x8e, 0x33, 0xaa, 0xef, 0xcb, 0x11, 0x4e, 0x78, 0x41, 0x18,
	0xe8, 0x91, 0x8c, 0x29, 0x23, 0x3a, 0xed, 0x64, 0x52, 0x24, 0x24, 0xe3, 0x64, 0xd5, 0x9f, 0xed,
	0x4a, 0x3d, 0x3b, 0xce, 0xa8, 0x62, 0xba, 0x74, 0xf8, 0x12, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x59,
	0x2e, 0xbc, 0xd5, 0x02, 0x00, 0x00,
}
