// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/util/example_proto_fast_parsing_test.proto

package util

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	example "github.com/netbrain/tf-grpc/go/tensorflow/tensorflow/go/core/example"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This message is parallel to Example, but with additional fields to test
// unknown fields handling in example_proto_fast_parsing_test.cc.
type ExampleWithExtras struct {
	Features             *example.Features `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	Extra1               string            `protobuf:"bytes,1337,opt,name=extra1,proto3" json:"extra1,omitempty"`
	Extra2               int64             `protobuf:"varint,1338,opt,name=extra2,proto3" json:"extra2,omitempty"`
	Extra3               uint32            `protobuf:"fixed32,1339,opt,name=extra3,proto3" json:"extra3,omitempty"`
	Extra4               uint64            `protobuf:"fixed64,1340,opt,name=extra4,proto3" json:"extra4,omitempty"`
	Extra5               float64           `protobuf:"fixed64,1341,opt,name=extra5,proto3" json:"extra5,omitempty"`
	Extra6               []float32         `protobuf:"fixed32,1342,rep,packed,name=extra6,proto3" json:"extra6,omitempty"`
	Extra7               *example.Features `protobuf:"bytes,1343,opt,name=extra7,proto3" json:"extra7,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExampleWithExtras) Reset()         { *m = ExampleWithExtras{} }
func (m *ExampleWithExtras) String() string { return proto.CompactTextString(m) }
func (*ExampleWithExtras) ProtoMessage()    {}
func (*ExampleWithExtras) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1031c2dac6823ae, []int{0}
}

func (m *ExampleWithExtras) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleWithExtras.Unmarshal(m, b)
}
func (m *ExampleWithExtras) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleWithExtras.Marshal(b, m, deterministic)
}
func (m *ExampleWithExtras) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleWithExtras.Merge(m, src)
}
func (m *ExampleWithExtras) XXX_Size() int {
	return xxx_messageInfo_ExampleWithExtras.Size(m)
}
func (m *ExampleWithExtras) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleWithExtras.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleWithExtras proto.InternalMessageInfo

func (m *ExampleWithExtras) GetFeatures() *example.Features {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *ExampleWithExtras) GetExtra1() string {
	if m != nil {
		return m.Extra1
	}
	return ""
}

func (m *ExampleWithExtras) GetExtra2() int64 {
	if m != nil {
		return m.Extra2
	}
	return 0
}

func (m *ExampleWithExtras) GetExtra3() uint32 {
	if m != nil {
		return m.Extra3
	}
	return 0
}

func (m *ExampleWithExtras) GetExtra4() uint64 {
	if m != nil {
		return m.Extra4
	}
	return 0
}

func (m *ExampleWithExtras) GetExtra5() float64 {
	if m != nil {
		return m.Extra5
	}
	return 0
}

func (m *ExampleWithExtras) GetExtra6() []float32 {
	if m != nil {
		return m.Extra6
	}
	return nil
}

func (m *ExampleWithExtras) GetExtra7() *example.Features {
	if m != nil {
		return m.Extra7
	}
	return nil
}

func init() {
	proto.RegisterType((*ExampleWithExtras)(nil), "tensorflow.ExampleWithExtras")
}

func init() {
	proto.RegisterFile("tensorflow/core/util/example_proto_fast_parsing_test.proto", fileDescriptor_f1031c2dac6823ae)
}

var fileDescriptor_f1031c2dac6823ae = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0x07, 0x70, 0xb2, 0x41, 0x7f, 0x3f, 0xe3, 0xc9, 0x22, 0x18, 0x3c, 0x15, 0x41, 0xe8, 0x65,
	0x8d, 0xb6, 0xdb, 0x04, 0x6f, 0x0a, 0xdb, 0x0b, 0xd8, 0x45, 0xf0, 0x52, 0xd2, 0x92, 0x76, 0x81,
	0xae, 0x29, 0xc9, 0x53, 0xdc, 0x6b, 0xf0, 0x1d, 0xf9, 0xff, 0x6d, 0x79, 0x94, 0x6c, 0x0f, 0xe9,
	0xf0, 0xe0, 0xad, 0xcd, 0xe7, 0xf9, 0x7e, 0x21, 0x4f, 0xe8, 0x2d, 0xc8, 0xd6, 0x6a, 0x53, 0x35,
	0xfa, 0x89, 0x97, 0xda, 0x48, 0xde, 0x83, 0x6a, 0xb8, 0xdc, 0x8a, 0x4d, 0xd7, 0xc8, 0xbc, 0x33,
	0x1a, 0x74, 0x5e, 0x09, 0x0b, 0x79, 0x27, 0x8c, 0x55, 0x6d, 0x9d, 0x83, 0xb4, 0x90, 0xec, 0xce,
	0x43, 0x3a, 0x64, 0xcf, 0x2f, 0x7f, 0xf7, 0x60, 0x05, 0xaf, 0xa4, 0x80, 0xde, 0xc8, 0x7d, 0xe4,
	0xe2, 0x79, 0x44, 0x4f, 0x16, 0x7b, 0x79, 0x50, 0xb0, 0x5e, 0x6c, 0xc1, 0x08, 0x1b, 0x5e, 0xd1,
	0xff, 0x38, 0x66, 0x19, 0x89, 0x48, 0x7c, 0x9c, 0x9e, 0x26, 0x43, 0x5f, 0xb2, 0x44, 0x5b, 0xf9,
	0xa9, 0xf0, 0x8c, 0x06, 0xd2, 0x65, 0xaf, 0xd9, 0x0b, 0x8d, 0x48, 0x7c, 0xb4, 0xc2, 0x5f, 0x0f,
	0x29, 0x7b, 0x75, 0x30, 0x46, 0x48, 0x3d, 0x64, 0xec, 0xcd, 0xc1, 0x3f, 0x84, 0xcc, 0xc3, 0x94,
	0xbd, 0x3b, 0x08, 0x10, 0xa6, 0x1e, 0x66, 0xec, 0xc3, 0x01, 0x41, 0x98, 0x79, 0x98, 0xb3, 0x4f,
	0x1a, 0x8d, 0xe3, 0x11, 0xc2, 0x3c, 0x9c, 0x20, 0xdc, 0xb0, 0x2f, 0xfa, 0xc7, 0x35, 0x70, 0xe8,
	0x7e, 0xf9, 0x78, 0x57, 0x2b, 0x58, 0xf7, 0x45, 0x52, 0xea, 0x0d, 0x6f, 0x25, 0x14, 0x46, 0xa8,
	0x96, 0x43, 0x35, 0xa9, 0x4d, 0x57, 0xf2, 0x5a, 0xf3, 0x83, 0xa5, 0x1e, 0x7c, 0xd6, 0x7a, 0x78,
	0xaa, 0x6f, 0x42, 0x8a, 0x60, 0xb7, 0xdb, 0xec, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xb0, 0x9a,
	0x25, 0xcc, 0x01, 0x00, 0x00,
}
